### ISSUE TITLE
Parse gender and proportions from a costumesave file

### ISSUE THREAD

**Issue by Jerricha** [Jerricha/jerrichas#2]
**Batch mode** doesn't support updating the gender and proportions from a `/costumesave` csv file. It's most likely encoded in one of the columns. We just have to figure out which column corresponds to it.

Update the mapper in `jerrichas.Costumesave.get_costumeparts` to reflect your results. 
These will be mapped onto the following columns in the database's `costume` table:

```
bodytype
skincolor
bodyscale
bonescale
headscale
shoulderscale
chestscale
waistscale
hipscale
legscale
headscales
browscales
cheekscales
chinscales
craniumscales
jawscales
nosescales
```

**Comment by ROBOKiTTY** [comment]
Gender is encoded in bodytype, which is row[7].

bonescale: row[10]
shoulderscale: row[12]
chestscale: row[13]
waistscale: row[14]
hipscale: row[15]
legscale: row[16]

headscales: row[18~20]
browscales: row[21-23]
cheekscales: row[24-26]
chinscales: row[27-29]
craniumscales: row[30-32]
jawscales: row[33-35]
nosescales: row[36-38]

headscales~nosescales are each an array of three signed fixed precision (up to 4th decimal digit) decimals in the csv, but they are stored as single integers in the database. Need to poke CW on this one.

**Comment by Jerricha** [comment]
Thanks ROBOKiTTY! Well regarding integer conversions, [Noyjitat says](http://www.cohtitan.com/forum/index.php/topic,11165.msg188614.html#msg188614):

> To change colors of your costume parts and FX. You will need to use Blue Green and Red format like the normal costume files use and take the 3 numbers; Multiply blue by 65536  green by 256 and add them together. White would be255,255,255 = 255_65536 + 255_256 + 255 = 16777215. Take that final number (in this case for white) and place it in the first color tab if that was your primary color. Refer to my picture above if you were wanting color one of the pants to be white. You'd place it in the same row as the pants geometry in color 1 column. Thank you Leandro for the explanation of changing color.

I wonder if the conversion works something similar for the face scales?

**Comment by ROBOKiTTY** [comment]
Conversion for headscales ~ nosescales et al should work like this, in pseudo-C:

float headscales[] = {row[18], row[19], row[20]};
int headscale_as_int = (signed char) (headscales[2] \* 100) << 16 | (signed char) (headscales[1] \* 100) << 8 | (signed char) (headscales[0] \* 100);

In case we need to convert it back:

float headscales[] = {0f, 0f, 0f};
headscales[0] = (headscale_as_int & 0xFF) / 100f;
headscales[1] = ((headscale_as_int >> 8) & 0xFF) / 100f;
headscales[2] = ((headscale_as_int  >> 16) & 0xFF) / 100f;

Minor discrepancy when back-converting since the original values are stored up to fourth decimal digit, but this encoding only keeps up to second decimal digit.

Edit: I forgot to test for negative values. Working code below.

**Comment by Jerricha** [comment]
~~KiTTY, what about `bodyscale`?~~

`bodyscale=row[9]`

**Comment by ROBOKiTTY** [comment]
So after some manual testing, Python translation of the above C code is almost identical:

scale_as_int = int(scales[2] * 100) << 16 | int(scales[1] * 100) << 8 | int(scales[0] * 100)

Back-conversion:

scales[0] = (scale_as_int & 0xFF) / 100.0
scales[1] = ((scale_as_int >> 8) & 0xFF) / 100.0
scales[2] = ((scale_as_int & >> 16) 0xFF) / 100.0

**Comment by ROBOKiTTY** [comment]
Fixed code.
is_clamped -- return x > -1 && x < 1
signum -- return (x > 0) - (x < 0)

``` c
    float headscales[] = {0, 0, 0};
    int headscale_as_int = 640523;
    headscales[0] = is_clamped((headscale_as_int & 0xFF) / 100) ?
        (headscale_as_int & 0xFF) / 100.0 :
        (headscale_as_int & 0x7F) / -100.0;
    headscales[1] = is_clamped(((headscale_as_int >> 8) & 0xFF) / 100) ?
        ((headscale_as_int >> 8) & 0xFF) / 100.0 :
        ((headscale_as_int >> 8) & 0x7F) / -100.0;
    headscales[2] = is_clamped(((headscale_as_int >> 16) & 0xFF) / 100) ?
        ((headscale_as_int >> 16) & 0xFF) / 100.0 :
        ((headscale_as_int >> 16) & 0x7F) / -100.0;

    int as_int = 0;
    as_int += (signum(headscales[0]) == -1) ?
        ( (int) ( abs(headscales[0]) * 100 ) | 0x80 ) :
        ( (int) ( abs(headscales[0] * 100) ) | 0 );
    as_int += (signum(headscales[1]) == -1) ?
        ( (int) ( abs(headscales[1]) * 100 ) | 0x80 ) << 8 :
        ( (int) ( abs(headscales[1] * 100) ) | 0 ) << 8;
    as_int += (signum(headscales[2]) == -1) ?
        ( (int) ( abs(headscales[2]) * 100 ) | 0x80 ) << 16 :
        ( (int) ( abs(headscales[2] * 100) ) | 0 ) << 16;
```

Python translation:

``` python
is_clamped = lambda x: -1 < x < 1
signum = lambda x: x and (1, -1)[x < 0]

headscales = [0.0, 0.0, 0.0]
headscale_as_int = 640523
headscales[0] = (headscale_as_int & 0xFF) / 100.0\
                if is_clamped((headscale_as_int & 0xFF) / 100)\
                else (headscale_as_int & 0x7F) / -100.0
headscales[1] = ((headscale_as_int >> 8) & 0xFF) / 100.0\
                if is_clamped(((headscale_as_int >> 8) & 0xFF) / 100)\
                else ((headscale_as_int >> 8) & 0x7F) / -100.0
headscales[2] = ((headscale_as_int >> 16) & 0xFF) / 100.0\
                if is_clamped(((headscale_as_int >> 16) & 0xFF) / 100)\
                else ((headscale_as_int >> 16) & 0x7F) / -100.0

as_int = 0
as_int += int(abs(headscales[0] * 100)) | 0x80\
          if signum(headscales[0]) == -1\
          else int(abs(headscales[0] * 100)) | 0
as_int += (int(abs(headscales[1] * 100)) | 0x80) << 8\
          if signum(headscales[1]) == -1\
          else (int(abs(headscales[1] * 100)) | 0) << 8
as_int += (int(abs(headscales[2] * 100)) | 0x80) << 16\
          if signum(headscales[2]) == -1\
          else (int(abs(headscales[2] * 100)) | 0) << 16
```
